# server的配置
server:
  servlet:
    context-path: /kitchen
  port: 8081

# 开启的配置
spring:
  profiles:
    active: dev
  # 修改默认的静态寻址资源目录
  resources:
    static-locations: classpath:/static/image/
  # 静态文件请求匹配方式
  mvc:
    static-path-pattern: /static/image/**
# api框架配置
swagger:
  # 扫描这些包下面的  接口类 和 实体类
  basePath: com.dhf
  title: API
  description: '厨阁 API'
  version: V1.0

#shiro整合redis
shiro-redis:
  enabled: true

# jwt的属性
markerhub:
  jwt:
    # 加密秘钥
    secret: f4e2e52034348f86b67cde581c0f9eb5
    # token有效时长，7天，单位秒
    expire: 604800
    header: token
